# Site settings
title: STAT Lab @JW
header-img: "img/cover.jpg"
tagline: "cn"  
description: "Jiayu WU | Exploration and Notes"  
baseurl: ""
url: "http://alice86.github.io"  

# About/contact
owner: 
  name: " zhichaoluo"
  email: "wujiayu86@outlook.com"
  bio: "Statistics Learner, BS&BA in XMU - MS in UCLA"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

#douban_username:  
#twitter_username: 
github_username: JiayuWu
facebook_username: Jiayu Wu
#weibo_username: 
#zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "jiayuwu"
      header-img: "img/blue.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : cnfeat
  disqus :
      short_name : cnfeat

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
