---
title: "Preface"
author: "Jiayu Wu"
date: "2017/9/21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface

This is a personal blog for my exploration and notes on statistics and data science study.

The site is created with github and the repository is forked from my dear teacher Zhichao Luo http://rokia.org/.   
Hearful thanks to him who introduced to me the immense possibilities in computational statistics and offer me generous help along this trip.

When I chose statistics as my minor in university, I regarded it as merely a more promising - by "promising" I mostly mean financially - profession than my major in Enlish.   
Well, I still think so. While I gradually came to appreciate Statistics as a subject that is rigorous and creative at the same time, and find it an incredibly elegant as well as pragmatic means of problem solving. 

Even before I realize, my utilitarian decision became a serious choice for my profession and future career. It's hard to mention certain significant turing point, and I won't say it's a completely inspirational story. However, I was enjoy it most of the time, and I am really glad I did push myself a bit to achieve what I am now.

It's my second week in LA and last night I met most of my classmates. They are so outstanding that I was wondering why it is even possible for me to be a part of this community. I feel exiting and proud, also pressured. 

I am determined to get on with the journey, and I set up this blog to record my gains and progress, to motivate further and countinuous effort, and to communicate with other learners.   
To start with, I am reviewing and consolidate R programming by reading through Advanced R by Hadley Wickmen. "Notes on R" will be the first series on this blog.

Jiayu Wu
Sep.21, 2017 Los Angeles